### ISSUE TITLE
Error while installing using pip: `FileNotFoundError: [Errno 2] No such file or directory: './requirements/requirements.txt'`

### ISSUE THREAD

**Issue by sanjayankur31** [nest/NEAT#141]
Hello,

As part of the [Fedora package review](https://bugzilla.redhat.com/show_bug.cgi?id=2056447), I was checking to see if I could install NEAT using pip. On Python 3.10, here, I run into this error:

```
$ pip install neatdend             
Collecting neatdend                                                                                                                       Using cached neatdend-0.9.1.tar.gz (172 kB)                       
  Preparing metadata (setup.py) ... error                                                                                                 ERROR: Command errored out with exit status 1:                    
   command: /home/asinha/.local/share/virtualenvs/neat-test/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-34r9ggyq/neatdend_980609061e344ed290e1a6bc2b9d6acc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-34r9ggyq/neatdend_9806
09061e344ed290e1a6bc2b9d6acc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code
, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-qfvmalj5                                                               cwd: /tmp/pip-install-34r9ggyq/neatdend_980609061e344ed290e1a6bc2b9d6acc/                                                        
  Complete output (7 lines):                                                                                                            
  Traceback (most recent call last):                                
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-34r9ggyq/neatdend_980609061e344ed290e1a6bc2b9d6acc/setup.py", line 121, in <module>
      install_requires=read_requirements(),
    File "/tmp/pip-install-34r9ggyq/neatdend_980609061e344ed290e1a6bc2b9d6acc/setup.py", line 63, in read_requirements
      with open('./requirements/requirements.txt') as fp:
  FileNotFoundError: [Errno 2] No such file or directory: './requirements/requirements.txt'
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/87/69/a4b6faad40fd3170c4bdc9113fc5d1b35d4f2057a4a508f8a724c0f91b71/neatdend-
0.9.1.tar.gz#sha256=3044ca6c72e8405cf72193ced2cbdb2fa89e2fe1c7ec7a6c42265d057797e7b1 (from https://pypi.org/simple/neatdend/). Command e
rrored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

It does not cause the installation to fail, however. The installation proceeds, and NEAT is installed in the virtualenv.

**Comment by terhorstd** [comment]
This could be caused by a `setup.py ` still containing some settings. Ideally these would all be moved to `pyproject.toml` and no `setuptools` would be involved anymore.
@steffengraber did you see such a message in your tests somewhere?

**Comment by WillemWybo** [comment]
Deprecated
